[package]
name = "file-server-bounty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url-escape = "0.1.1"
mime_guess = "2.0.3"